const TOPIC_KEYWORDS: Record<string, string[]> = {
  defending: [
    "defend",
    "defending",
    "defensive",
    "tackle",
    "tackling",
    "press",
    "pressing",
    "block",
    "intercept",
    "marking",
    "offside trap",
    "back four",
    "centre back",
    "centerback",
    "full back",
    "fullback",
  ],
  attacking: [
    "attack",
    "attacking",
    "offensive",
    "counter",
    "counterattack",
    "build up",
    "build-up",
    "transition",
    "wing play",
    "overload",
    "overlap",
    "underlap",
  ],
  passing: [
    "pass",
    "passing",
    "possession",
    "rondo",
    "tiki-taka",
    "through ball",
    "switch",
    "distribution",
    "short pass",
    "long pass",
    "ball retention",
  ],
  "set pieces": [
    "set piece",
    "set-piece",
    "corner",
    "free kick",
    "freekick",
    "throw in",
    "throw-in",
    "penalty",
    "dead ball",
  ],
  formation: [
    "formation",
    "4-3-3",
    "4-4-2",
    "3-5-2",
    "4-2-3-1",
    "3-4-3",
    "4-1-4-1",
    "shape",
    "system",
    "tactical",
    "structure",
  ],
  "age groups": [
    "u7",
    "u8",
    "u9",
    "u10",
    "u11",
    "u12",
    "u13",
    "u14",
    "u15",
    "u16",
    "u17",
    "u18",
    "under 7",
    "under 8",
    "under 9",
    "under 10",
    "under 11",
    "under 12",
    "grassroots",
    "youth",
    "junior",
    "mini soccer",
    "kids",
    "children",
  ],
  goalkeeping: [
    "goalkeeper",
    "goalkeeping",
    "keeper",
    "gk",
    "shot stopping",
    "distribution",
    "diving",
    "handling",
    "goal kick",
  ],
  fitness: [
    "fitness",
    "conditioning",
    "warm up",
    "warm-up",
    "cool down",
    "cool-down",
    "endurance",
    "speed",
    "agility",
    "stamina",
    "strength",
    "injury",
    "prevention",
    "recovery",
  ],
  laws: [
    "law",
    "rule",
    "offside",
    "handball",
    "foul",
    "red card",
    "yellow card",
    "var",
    "referee",
    "ifab",
    "penalty",
    "dangerous play",
    "advantage",
    "caution",
    "sending off",
  ],
  scouting: [
    "scout",
    "scouting",
    "player stats",
    "statistics",
    "transfer",
    "talent",
    "recruitment",
    "xg",
    "expected goals",
    "performance",
    "data",
    "analytics",
  ],
  "session planning": [
    "session plan",
    "training plan",
    "session",
    "drill",
    "exercise",
    "practice",
    "coaching session",
    "training session",
    "warm up drill",
  ],
  "player development": [
    "player development",
    "technical",
    "technique",
    "ball mastery",
    "first touch",
    "dribbling",
    "shooting",
    "heading",
    "turning",
    "receiving",
    "1v1",
    "one v one",
  ],
};

export function extractTopics(queryText: string): string[] {
  const lower = queryText.toLowerCase();
  const topics: string[] = [];

  for (const [topic, keywords] of Object.entries(TOPIC_KEYWORDS)) {
    for (const keyword of keywords) {
      if (lower.includes(keyword)) {
        topics.push(topic);
        break;
      }
    }
  }

  return topics;
}

export function getTopicKeywords(): Record<string, string[]> {
  return TOPIC_KEYWORDS;
}
